class_weight:
- balanced
criterion:
- gini
file_name: wrist_erosion_1503
id_dir: SHS_AI_wristE_s0.1_d0.6
max_depth: '[i for i in range(3,6,1)]'
max_features:
- log2
- sqrt
max_iter: 800
max_leaf_nodes: '[i for i in range(4,6,1)]'
min_samples_split: '[i for i in range(3,5,1)]'
n_estimators: '[20, 60, 100, 140, 180]'
name: SHS_NET_wrist_erosion
num_fold: 10
perc: 70
random_state:
- 1
